config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'

  get 'auth/:provider/callback', to: 'sessions#create'
  post 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  get '/login', to: 'sessions#new'
  get 'auth/identity/', to: redirect('/login')
  resources :identities, only: [:new, :create]
  
  get '/add-a-book', to: 'books#new'
  post '/add-a-book', to: 'books#new'

  get '/explore', to: 'users#index'
  
  post 'read', to: 'user_books#create'
  post 'delete_book', to: 'user_books#destroy'


  resources :books, only: [:create]

  resources :users, except: [:index, :new, :create, :destroy] do  
    member do
      resources :relationships, only: [:create, :destroy]
      get :following, :followers
    end
  end
  
end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    @popular_users = sort_users_by_followers
    render :layout => 'landing'
  end
end

app/views/static_pages/_explore.html.erb
<%= link_to "/explore" do %>
  <ul class='list-inline explore-list'>
    <li><img style='height:25px;' src='/assets/images/icons/bino_explore.png'/></li>
    <li><p class="paragraph" id="explore">EXPLORE LIBRARIES </p></li>
    <li><img src='/assets/images/icons/explore_arrow.png'/></li>
  </ul>
<% end %>

app/views/static_pages/_index_navigation.html.erb
<nav class='navbar nav-inner'>
  <ul class='list-inline '>

    <li class="nav nav-item navbar-left">
      <h3><%= link_to "Explore", '/explore' %></h3> 
    </li>

    <li class="nav nav-item navbar-center">
      <%= link_to root_path do %>
        <h3 id="title">Bookself</h3>
      <% end %>
    </li>


    <li class='nav nav-item navbar-right'>
      <ul class='list-inline'>
        <% if current_user %>
          <li><h3><%= link_to "#{current_user.first_name}", user_path(current_user) %><h3></li>
          <li><%= link_to "Sign out", signout_path %></li> 
        <% else %>
          <li><h3><%= link_to "Sign in", '/auth/facebook' %><h3></li>
        <% end %>
      </ul>
    </li>  
     
  </ul>
</nav>
    

app/views/static_pages/_inspired.html.erb
<section class='home-last-call black'>
  <h1>Insipired yet?</h1>
  <p class="paragraph">Start following people and see what they're reading.</p>
  <div style='margin-top:30px;'>

    <% if current_user %>
      <%= link_to user_path(current_user)  do %>
        <img class='center-block custom-button' src='/assets/images/icons/button_gotobookshelf_blue.png'/>
      <% end %>
    <% else %>
      <%= link_to "/auth/facebook", id: "sign_in" do %>
        <img class='center-block custom-button' src='/assets/images/icons/button_create_home_blue.png'/>
      <% end %>
    <% end %>
    
  </div>
</section>

app/views/static_pages/index.html.erb
<div id='home-page'>

  <section class='home-top white'>
    <h1 class="title">Books. Pass 'em on.</h1>
    <p class="paragraph">Find the best reads from your friends and inspirations.</br>
       Recommend books to people you know.</p>
    <div>
      <% if current_user %>
        <%= link_to user_path(current_user)  do %>
          <img class='center-block custom-button' src='/assets/images/icons/button_go_to_home.png'/>
        <% end %>
      <% else %>
        <%= link_to "/auth/facebook", id: "sign_in" do %>
          <img class='center-block custom-button' src='/assets/images/icons/button_create_home.png'/>
        <% end %>
      <% end %>
    </div>
  </section>

  <section class='home-middle black'>
    <h1 class='title'>Algorithms only go so far.</h1>
    <p class="paragraph">Explore freinds and inspirational people's bookshelves,</br>
    get personal recommendations and pass 'em on.</p>

    <%= render 'static_pages/explore',:layout => 'landing' %>

    <img src="" id="book-row-landing"/>
  </section>

  <section class='home-quote white'>
    <h2 class="quote">"If we encounter a man of rare intellect,</br>we should ask him what books he reads."</h2>
    <p class="paragraph" id="quote-name">RALPH WALDO EMERSON</p>
  </section>

  <section class='home-bottom black'>
    <h1 >Try it for yourself.</h1>
    <p class="paragraph">Create your bookshelf and receive recommendations.</p>

    <div style='margin-top:30px;'>
      <% if current_user %>
        <%= link_to user_path(current_user)  do %>
          <img class='center-block custom-button' src='/assets/images/icons/button_gotobookshelf_blue.png'/>
        <% end %>
      <% else %>
        <%= link_to "/auth/facebook", id: "sign_in" do %>
          <img class='center-block custom-button' src='/assets/images/icons/button_create_home_blue.png'/>
        <% end %>
      <% end %>
    </div>
  </section>

  <%= render 'users/index_block' %>
  <%= render 'inspired' %>
  
</div>