config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'

  get 'auth/:provider/callback', to: 'sessions#create'
  post 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  get '/login', to: 'sessions#new'
  get 'auth/identity/', to: redirect('/login')
  resources :identities, only: [:new, :create]
  
  get '/add-a-book', to: 'books#new'
  post '/add-a-book', to: 'books#new'

  get '/explore', to: 'users#index'
  
  post 'read', to: 'user_books#create'
  post 'delete_book', to: 'user_books#destroy'


  resources :books, only: [:create]

  resources :users, except: [:index, :new, :create, :destroy] do  
    member do
      resources :relationships, only: [:create, :destroy]
      get :following, :followers
    end
  end
  
end

app/models/user.rb
class User <ActiveRecord::Base
  validates_presence_of :first_name, :last_name
  validates :email, uniqueness: true  
  before_save :generate_slug
  
  has_many :user_books
  has_many :books, through: :user_books
  has_many :active_relationships,  class_name:  "Relationship",
                                   foreign_key: "follower_id",
                                   dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  has_attached_file :avatar, 
                    :styles => { :medium => "200x200>", :thumb => "100x100>" }, 
                    :default_url => ""
  has_attached_file :cover, 
                    :styles => { :medium => "768x", :small => "400x" }, 
                    :default_url => ""
  has_attached_file :download,
                    :storage => :s3,
                    :s3_credentials => {:bucket => "bookself-avatars", 
                                        :access_key_id => ENV['AWS_ACCESS_KEY_ID'], 
                                        :secret_access_key => ENV['AWS_SECRET_KEY']}

  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  validates_attachment_content_type :cover,  :content_type => /\Aimage\/.*\Z/
  
  # Creating users through Omniauth
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider   = auth.provider
      user.uid        = auth.uid
      user.first_name = auth.info.first_name
      user.last_name  = auth.info.last_name
      user.email      = auth.info.email
      if auth.provider == "facebook"
        user.image      = auth.info.image + "?type=large"
        user.token      = auth.credentials.token
        user.expires_at = Time.at(auth.credentials.expires_at)
      end
      user.random_color
      user.save!
    end
    # This is here so that the "provider" is not taken into account when seraching for users in 'generate_slug'.
    # This way, users from different providers will not have the same slug.
    u = User.last
    u.generate_slug
    u.save!
    return User.where(provider: auth.provider, uid: auth.uid).first
  end

  # Followers / Following methods
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  # Methods to compare users amongst themselves
  def self.search(search)
    if search == ""
    elsif search
      key = "%#{search}%"
      where('first_name LIKE :search OR last_name LIKE :search', search: key)
    else
    end
  end

  def same_books(user)
    current_user_books = self.books.uniq
    user_books         = user.books.uniq
    same_books = current_user_books & user_books
  end

  def number_of_same_books(user)
    current_user_books = self.books.uniq
    user_books         = user.books.uniq
    different_books    = (current_user_books - user_books).count
    if different_books < 0
      different_books =  different_books*-1
    end 
    same_books_total = current_user_books.count - different_books
    return same_books_total
  end

  # Slug-related methods
  def to_param
    self.slug
  end

  def generate_slug
    the_slug = to_slug(self.first_name.to_s + self.last_name.to_s)
    object   = User.find_by slug: the_slug
    count    = 2
      while object && object !=self
        the_slug = append_suffix(the_slug, count)
        object   = self.class.find_by slug: the_slug
        count    += 1 
      end
    self.slug = the_slug.downcase
  end

  def append_suffix(str, count)
    if str.split('-').last.to_i != 0
      return str.split('-').slice(0...-1).join('-') + "-" + count.to_s
    else
      return str + "-" + count.to_s
    end
  end

  def to_slug(name)
    str = name.strip
    str.gsub! /\s*[^A-Za-z0-9]\s*/, '-'
    str.gsub! /-+/, '-'
    str.gsub! /^-+|-+$/, ''
    str.downcase
  end

  # Methods regarding the user's color or cover
  def random_color
    self.color = ["#80b891", "#f89f81", "#586576", "#f0d2a8"].sample
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user,     only: [:show, :update, :edit, :followers, :following]
  before_action :require_user, only: [:edit, :update, :following, :followers]

  def index
    @popular_users  = sort_users_by_followers
    @searched_users = User.search(params[:search])
    render :layout  => 'landing'
  end
  
  def show
    case params[:tab]
    when 'books'
      if logged_in?
        @books = current_user.same_books(@user)
      else
        return_books("read")
      end
    when 'to-read'
      return_books("to-read")
    when 'following'
      following
    when 'followers'
      followers
    else
      return_books("read")
    end
  end

  def edit
    unless @user.provider == "identity"
      redirect_to root_path
    end
  end

  def update
    # Update is only available for "fake users" right now
    if @user.provider    != "identity"
      redirect_to root_path
    elsif @user.provider == "identity"
      @user.update(user_params)
      @user.image     = "#{@user.avatar.url(:medium)}"
      @user.save!
      flash[:success] = "Your profile was updated successfully."
      redirect_to user_path
    else
      flash[:danger]  = "Something went wrong. Please try again."
      render :edit
    end
  end

  def following
    @following = @user.following.sort_by do |user| 
      if current_user
        current_user.number_of_same_books(user)
      else
        user.followers.count
      end
    end
    @following.reverse!
  end

  def followers
    @followers = @user.followers.sort_by do |user| 
      if current_user
        current_user.number_of_same_books(user)
      else
        user.followers.count
      end
    end
    @followers.reverse!
  end

  private

  def set_user
    @user = User.find_by(slug: params[:id])
  end

  def return_books(status)
    @books = []
    user_books = @user.user_books.order('user_books.updated_at desc').where(status: status)
    user_books.each do |ub|
      book = Book.find_by(id: ub.book_id)
      @books << book
    end
    @books
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :password, :password_confirmation, :description, :image, :avatar, :cover, :slug)
  end

end

app/views/users/_carousel.html.erb
<div id="carousel-example-generic" class="carousel slide big-photo" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img class="carousel-image center-block" id="" src="https://thenypost.files.wordpress.com/2013/10/gates.jpg" alt="...">
      <div class="carousel-caption">
        <h1 class="carousel-name">Bill Gates -  Microsoft</h1>
        <h3 class="carousel-description">ENTREPRENEUR / PHILANTROPIST</h3>
        <%= link_to '#' do %>
          <img class="carousel-see-bookshelf custom-button center-block" src='/assets/images/icons/explore_see_his_bookshelf.png'/>
        <% end %>
      </div>
    </div>
    <div class="item">
      <img class="carousel-image center-block" src="https://thenypost.files.wordpress.com/2013/10/gates.jpg" alt="...">
      <div class="carousel-caption">
        <h1 class="carousel-name">Bill Gates -  Microsoft</h1>
        <h3 class="carousel-description">ENTREPRENEUR / PHILANTROPIST</h3>
        <%= link_to '#' do %>
          <img class="carousel-see-bookshelf  custom-button center-block" src='/assets/images/icons/explore_see_his_bookshelf.png'/>
        <% end %>
      </div>
    </div>
    <div class="item">
      <img class="carousel-image center-block" src="https://thenypost.files.wordpress.com/2013/10/gates.jpg" alt="...">
       <div class="carousel-caption">
        <h1 class="carousel-name">Bill Gates -  Microsoft</h1>
        <h3 class="carousel-description">ENTREPRENEUR / PHILANTROPIST</h3>
        <%= link_to '#' do %>
          <img class="carousel-see-bookshelf custom-button center-block" src='/assets/images/icons/explore_see_his_bookshelf.png'/>
        <% end %>
      </div>
    </div>
  </div>


  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
      <img class='left-arrow' src='/assets/images/icons/arrow_left_slider_explore.png'/>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <img class='right-arrow' src='/assets/images/icons/arrow_right_slider_explore.png'/>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/users/_empty_books.html.erb
<div class='container text-center'>
  <% if current_user_profile? %>
    <p>You don't have any books here yet.</p>
    <p class='box-button center-block'>
        <%= link_to "ADD YOUR FAVORITE BOOK", add_a_book_path %>
    </p>

  <% elsif logged_in? %>
    <h5>
      <%= @user.first_name %> doesn't have any books here yet.
    </h5>
    <%= link_to user_path(current_user) do %>
      <img class='center-block custom-button' src='/assets/images/icons/button_gotobookshelf_blue.png'/>
    <% end %>

  <% else %>
    <h5>
      <%= @user.first_name %> doesn't have any books here yet.
    </h5>
  <% end %>
  
  <%= render 'static_pages/explore', :layout => 'landing' %>
</div>

app/views/users/_empty_follow.html.erb
<div class='text-center'>
  <% if params[:tab] == "followers" %>
    <% if current_user_profile? %>
      <h4>You don't have any followers yet.</h4>
      <%= link_to user_path(current_user) do %>
        <img class='center-block custom-button' src='/assets/images/icons/button_gotobookshelf_blue.png'/>
      <% end %>

    <% else %>
      <h4>
        <%= @user.first_name %> doesn't have any followers yet.
      </h4>
      <%= form_for(current_user.active_relationships.build) do |f| %>
        <div>
          <%= hidden_field_tag :followed_id, @user.id %>
          <%= hidden_field_tag :@user, @user %>
        </div>
        <%= f.submit "Follow them", class: "btn btn-primary" %>
      <% end %>
    <% end %>

  <% elsif params[:tab] == "following" %>
    <% if current_user_profile? %>
      <h4>You're not following anyone yet.</h4>
      <p class='box-button center-block'>
        <%= link_to "FIND PEOPLE TO FOLLOW", explore_path %>
      </p>
    <% else %> 
      <h4>
        <%= @user.first_name %> isn't following anyone yet.
      </h4>
      <p class='box-button center-block'>
        <%= link_to "BACK TO THEIR BOOKSHELF", user_path(@user) %>
      </p>
    <% end %>
  <% end %>

  <%= render 'static_pages/explore',:layout => 'landing' %>
</div>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div>
    <%= hidden_field_tag :followed_id, @user.id %>
    <%= hidden_field_tag :@user, @user %>
  </div>
  <%= f.submit :type => :image, :src => "/assets/images/icons/follow.png", class: "follow-button" %>
<% end %>

app/views/users/_following_form.html.erb
<% unless current_user_profile? %>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render 'unfollow' %>
    <% else %>
      <%= render 'follow' %>
    <% end %>
  </div>
<% end %>

app/views/users/_index_block.html.erb
<div class='.big-photo'>
<%= render 'users/carousel' %>
</div>

<div id='user-search'>
  <form action='/explore' class='navbar-form form-inline'>
    <div class='form-group col-xs-9 col-sm-offset-1 col-xs-offset-0'>
      <input class='form-control search-bar' name='search' 
             placeholder="Find someone's bookshelf" style="width: 100%;" type='text'>
    </div>
      <button class='form-group btn btn-primary search-button' id='corner-button' type='submit'>
        SEARCH
      </button>
  </form>
</div>

<div class="container-fluid user-results">
  <div id="users">
    <%= render 'users/users_search' unless @searched_users.nil? %>
  </div>

  <h4 class='text-center' id="popular-title">POPULAR BOOKSHELVES</h4>
  <%= render 'users/user_cards', users: @popular_users %>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit :type => :image, :src => "/assets/images/icons/unfollow.png", class: "follow-button" %>
<% end %>

app/views/users/_user_books.html.erb
<% if (@books.nil? || @books.empty?) %>
  <%= render 'empty_books' %>
<% else %>

  <div class='all-books' >
    <% @books.each do |book| %>

      <div class='col-sm-3 col-xs-6 book-row'>

        <div class='profile-book'>
          <img class='img-responsive' src='<%= book.cover_image_link %>'>     
        </div>
      

        <div class='book-options'>
            <h4 class='hover-title'><%= book.title %></h4>
            <h4 class='hover-title'><%= book.authors %></h4>
            <div class='padding'></div>

            <% if logged_in? %>

              <% unless current_user_profile? && book.has_been_read_by?(current_user) %>
                <%= link_to read_path(user_book: {book_id: book.id, user_id: current_user.id, status: "read"}), method: :post do %>
                  <ul class='list-inline hover-book-item' id='read'>
                    <li class="hover-book-item"><img class='icon' src='/assets/images/icons/hover_tobookshelf.png'/></li>
                    <li class="hover-book-item"><h5 class='hover-text'>Add to bookshelf</h5></li>
                  </ul>
                <% end %>  
              <% end %>

              <% unless current_user_profile? && book.is_in_reading_list_of?(current_user) %>
                <%= link_to read_path(user_book: {book_id: book.id, user_id: current_user.id, status: "to-read"}), method: :post do %>
                  <ul class='list-inline' id='to-read'>
                    <li class="hover-book-item"><img class='icon' src='/assets/images/icons/hover_toread.png'/></li>
                    <li class="hover-book-item"><h5 class='hover-text' >Reading list</h5></li>
                  </ul>
                <% end %>
              <% end %>

              <% if current_user_profile? %>
                <%= link_to delete_book_path(user_book: {book_id: book.id, user_id: current_user.id}), method: :post do %>
                  <ul class='list-inline' id='remove'>
                    <li class="hover-book-item"><img class='icon' src='/assets/images/icons/hover_remove.png'/></li>
                    <li class="hover-book-item"><h5 class='hover-text' >Remove book</h5></li>
                  </ul>
                <% end %>
              <% end %>
            <% end %>

            <%= link_to book.amazon_link do %>
              <ul class='list-inline' id='buy'>
                <li class="hover-book-item"><img class='icon' src='/assets/images/icons/hover_buy.png'/></li>
                <li class="hover-book-item"><h5 class='hover-text' >Buy this book</h5></li>
              </ul>
            <% end %>

        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/users/_user_cards.html.erb
<section class='follower-card-container' >
  <% if users.nil? || users.empty? %>
    <%= render 'users/empty_follow', tab: params[:tab] %>
  <% else %>
  
    <!-- Clearly this will break once we have more than a couple users. -->
    <% users.each do |user| %>

      <div class='col-sm-4 col-xs-12 follower-card'>
        <%= link_to user_path(user) do %>

          <div id='color'>
          <% if user.cover.url.present? %>
            <img class='img-responsive' id='card-image' src="<%= user.cover(:small) %>"/>
          <% elsif user.color.present? %>
            <div style="background-color:<%= user.color %>; height:100px;"></div>
          <% else %>
            <div style="background-color:<%= random_color %>; height:100px;"></div>
          <% end %>
          </div>

          <div id='card-info'>

            <img class='img-responsive img-circle user-photo' src="<%= user.image %>"/>
            <h4 class='name-and-count' style='font-weight: bold;'><%= user.first_name + " " + user.last_name%></h4>
            <ul class='list-inline name-and-count' id='followers-books'>
              <li><h6><%= book_count(user) %></h6></li>
              <li><h6><%= user.followers.count %> followers</h6></li>
            </ul>

            <div class='card-books'>    
              <% if user.books.empty? %>
                <% 4.times do %>
                  <div class='col-xs-3 book-row'>
                    <img class='img-responsive' src="/assets/images/no-book.png"/>
                  </div>
                <% end %>

              <% elsif user.books.count < 4 %>
                <%= user.books.each do |book|%>
                  <div class='col-xs-3 book-row'>
                    <img class='img-responsive' src="<%= book.cover_image_link %>"/>
                  </div>
                <% end %>

              <% else %>
                <%= user.books[1..4].each do |book|%>
                  <div class='col-xs-3 book-row'>
                    <img class='img-responsive' src="<%= book.cover_image_link %>"/>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  <% end %>
</section>

app/views/users/_users_search.html.erb
<% if @searched_users.empty? %>
  <h4>Your search didn't return anyting.</br>
    Try using people's first or last names.
  </h4>
<% else %>
  <h4 class="text-center" style='margin-bottom:50px;'>
    RESULTS FOR "<%= params[:search] %>"
  </h4>
  <%= render 'user_cards', users: @searched_users %>
<% end %>

app/views/users/edit.html.erb
<div class='container' style='margin-top: 500px;'>

<h1>Update your profile</h1>

<%= form_for @user, :html => { :multipart => true } do |form| %>
  <h4>Profile picture</h4>
  <%= form.file_field :avatar %>
  <h4>Cover Picture</h4>
  <%= form.file_field :cover %>
  <h4>Description</h4>
  <%= form.text_field :description, class: 'col-sm-8' %>
</br></br>
  <%= form.submit "Submit" , class: 'btn btn-success' %>
<% end %>

</div>

app/views/users/index.html.erb
<%= render 'index_block' %>
<%= render 'static_pages/inspired' %>

app/views/users/show.html.erb
<div class='user-information'>

  <div class="text-center">
    <img class='img-circle' id='profile-photo' src='<%= @user.image %>'/>

    <div class='container'>
      <%= render 'layouts/messages' %> 
    </div>

    <h3><%= @user.first_name%> <%=@user.last_name%> </h3>
    <h5><%= @user.description unless @user.description.nil? %></h5>
    <% unless @user == current_user %>
      <%= link_to "#{book_count(@user)}", user_path(@user, tab: 'books') %>
    <% end %>
    <%= link_to "#{@user.followers.count} followers", user_path(@user, tab: 'followers') %>
    <%= render 'following_form' if logged_in? %>
    <% if @user == current_user %>
      <h5><%= link_to "ADD A BOOK", add_a_book_path %></h5>
    <% end %>
  </div>

<div class="text-center">
  <ul class='center-pills list-inline'>
      <li class='<%= 'active' if params[:tab].nil? %> tab'>
        <%= link_to "BOOKSHELF", user_path(@user) %>
      </li>
      
    <% unless @user.provider == 'identity' %>
      <li class='<%= 'active' if params[:tab] == 'to-read' %> tab'>
        <%= link_to "TO READ", user_path(@user, tab: 'to-read') %>
      </li>  
      <li class='<%= 'active' if params[:tab] == 'following' %> tab'>
        <%= link_to "FOLLOWING (#{@user.following.count})", user_path(@user, tab: 'following') %>
      </li>  
    <% end %>
  </ul>
</div>

  <% if params[:tab].nil? %>
    <%= render 'user_books', tab: "books"%>
  <% elsif params[:tab] == 'to-read' %>
    <%= render 'user_books', tab: "to-read" %>
  <% elsif params[:tab] == 'followers' %>
    <%= render 'user_cards', users: @followers %>
  <% elsif params[:tab] == 'following' %>
    <%= render 'user_cards', users: @following %>
  <% elsif params[:tab] == 'books' %>
    <%= render 'user_books' %>
  <% end %>
</div>